/* Action types */
export const actionTypes = {
  USERS_SAMPLE_FETCH: 'USERS/SAMPLE_FETCH',
  USERS_SAMPLE_FETCH_SUCCESS: 'USERS/SAMPLE_FETCH_SUCCESS',
  USERS_SAMPLE_FETCH_ERROR: 'USERS/SAMPLE_FETCH_ERROR',
  RESENT_FETCH:"RESENT_FETCH",
  RESENT_FETCH_SUCCESS:"RESENT_FETCH_SUCCESS",
  RESENT_FETCH_ERROR:"RESENT_FETCH_ERROR",
  ARTICLE_FETCH_CONTENT:"ARTICLE_FETCH_CONTENT",
  ARTICLE_FETCH_CONTENT_SUCCESS:"ARTICLE_FETCH_CONTENT_SUCCESS",
  ARTICLE_FETCH_CONTENT_ERROR:"ARTICLE_FETCH_CONTENT_ERROR",

};
